### ISSUE TITLE
Test failures with bouncycastle 1.70 on Fedora 36.

### ISSUE THREAD

**Issue by ellert** [eu-emi/canl-java#115]
The bouncycastle version in Fedora rawhide was updated to 1.70. The canl-java build fails with 2 failing tests:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpensslValidatorTest.testExpiredWithCrl:90 Other then two errors returned: FAILED The following validation errors were found:
error affecting the whole chain (category: X509_CHAIN): More then one trusted CA certificate was found for the certificate chain
error at position 0 in chain, problematic certificate subject: CN=Expired User,O=EMITest,C=EU (category: X509_CHAIN): Trusted issuer of this certificate was not established
error at position 0 in chain, problematic certificate subject: CN=Expired User,O=EMITest,C=EU (category: X509_BASIC): Certificate has expired on: Wed Jan 30 01:01:00 UTC 2013
error at position 0 in chain, problematic certificate subject: CN=Expired User,O=EMITest,C=EU (category: CRL): CRL for an expired certificate was not resolved Cause: No CRLs found for issuer "cn=The root CA1,o=EMITest,c=EU" expected:<2> but was:<4>
[ERROR]   RolloverTest.test:32 FAILED The following validation errors were found:
error affecting the whole chain (category: X509_CHAIN): More then one trusted CA certificate was found for the certificate chain
error at position 0 in chain, problematic certificate subject: CN=User1,O=EMITest,C=EU (category: X509_CHAIN): Trusted issuer of this certificate was not established
[INFO] 
[ERROR] Tests run: 272, Failures: 2, Errors: 0, Skipped: 3
```

**Comment by golbi** [comment]
Hi. 
I'm looking into it since some time. Finally found the root cause. It is it:
https://github.com/bcgit/bc-java/commit/911e5fae52b970d25761c55b30a5eb77c6ba09bd

and the change around 2485 line (plus see the commit message). It looks to me that it is broken: 
- (minor) the if is not needed (selector officially accepts null)
- if the parent HAS key id then it is not selected, even though child cert has it set. In effect you can have chain building problem, as algorithm will select multiple parents. What is exactly the case for the failing tests...

I can overwrite that, but will try to get some info from the author of that change first.

**Comment by ellert** [comment]
Is this recent commit to BC relevant for this:
https://github.com/bcgit/bc-java/commit/d1fb007090813ce348a2d439f12fa347a8d5010c

**Comment by ellert** [comment]
With the above commit backported to BC 1.70 the canl-java tests succeed.
canl-java now builds in Fedora 36 again.

**Comment by golbi** [comment]
yes, I've filled https://github.com/bcgit/bc-java/issues/1082 in BC
